Feature/jwt login service 최신화
IT-NOVATION/BackEnd pull request #22
Opened 2023-05-20 17:27 UTC by djc06048

### 자체 회원가입/로그인
1. `/signup`으로 회원가입이 가능합니다
2. `/login`으로 로그인이 가능합니다 
: 로그인 시 헤더에 `Authorization` 과 `Authorization-refresh`를 받아옵니다. 
이후 권한이 필요한 작업이 있을 때 `Authorization`을 넘겨 줍니다

### 소셜로그인
1. /oauth2/authorization/naver
2. /oauth2/authorization/kakao
3. /oauth2/authorization/google
로 로그인 후 리다이렉트 페이지로 이동합니다
데이터베이스에 같은 이메일이 존재할 경우 회원가입이 되지않습니다

2023-05-21 12:09 UTC, khyojun requested changes

2023-05-21 12:09 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
> +                .requestMatchers("/","/oauth2/**","/css/**", "/images/**", "/js/**").permitAll()
혹시 requireMatchers 에 /api/v1/movies 넣어줄 수 있을까요? ㅠㅠ
매번 테스트 때마다 넣고 빼고 해야되서 부탁드립니다👏👏

2023-05-21 14:39 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
> +                .requestMatchers("/","/oauth2/**","/css/**", "/images/**", "/js/**").permitAll()
넵 :) 저부분은 토큰 조금 더 공부후에 처리가능하게 할 예정인데 일단 넣어 놓겠습니다

2023-05-21 14:49 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
> +                .requestMatchers("/","/oauth2/**","/css/**", "/images/**", "/js/**").permitAll()
감사합니다 ㅎㅎ!

2023-05-21 14:50 UTC, khyojun approved these changes

2023-05-22 12:23 UTC, khyojun approved these changes

2023-05-22 12:23 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/common/controller/Person.java
> +package com.ItsTime.ItNovation.common.controller;
혹시 여기에 있는 common 이라는 폴더는 공통으로 다같이 사용한다는 의미로 사용한거야?

2023-05-22 12:34 UTC, J-neat approved these changes

2023-05-24 03:05 UTC, stakbucks commented
👍🔥🔥🔥🔥

2023-05-24 03:07 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/common/controller/Person.java
> +package com.ItsTime.ItNovation.common.controller;
저거 테스트용으로 폴더 뭐로 하지 하다가 API 응답이라서 common이라고 해놨어!
다른 적절한 이름 있으면 추천해줘도 돼 ㅎㅎ

2023-05-24 05:46 UTC, merged