Feature/jwt login service
IT-NOVATION/BackEnd pull request #26
Opened 2023-06-22 12:08 UTC by djc06048

로그인 성공시 리다이렉트 url 수정

2023-06-22 12:12 UTC, khyojun requested changes

2023-06-22 12:12 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
> +    public ResponseEntity<ApiResult<String>> signup(@RequestBody SignUpRequestDto signUpRequestDto) {
ResponseEntity에다가 ApiResult까지 넣은 이유가 있을까요?

2023-06-22 12:19 UTC, J-neat approved these changes
LGTM

2023-06-23 00:43 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
> +    public ResponseEntity<ApiResult<String>> signup(@RequestBody SignUpRequestDto signUpRequestDto) {
나중에 형식 통일하려고 했는데 그냥 성공 실패 메시지 말고 바디에 필요한 내용만 전달하는게 좋을까요?

2023-06-23 05:03 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/user/UserController.java
> +    public ResponseEntity<ApiResult<String>> signup(@RequestBody SignUpRequestDto signUpRequestDto) {
네네 ResponseEntity 자체에 ApiResult 안에 있는 내용에 대해서는 설정할 수 있을거 같아서요!

2023-06-23 06:04 UTC, djc06048 reviewed
커멘트 반영 완료했습니다

2023-06-23 06:06 UTC, khyojun approved these changes

2023-06-23 06:07 UTC, merged