Feature/search movie
IT-NOVATION/BackEnd pull request #32
Opened 2023-06-29 13:10 UTC by J-neat

영화 검색 기능 추가

2023-07-02 06:58 UTC, djc06048 requested changes

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
이 부분 movie 검색하는 부분은 토큰이 필요없어서 .permitAll에 등록하는건 맞지만 /search/movie 이렇게 그냥 수정해주세요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieSearchController.java
이 부분도 private final MovieSearchService movieSearchService, @RequiredArgsConstructor 롬복 어노테이션을 사용하면 final 로 선언된 필드에 대한 의존성 주입을 위한 생성자가 자동으로 설정되므로 이렇게 변경하면 좋을거같아요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieSearchController.java
이 경우 필드 선언만으로도 생성자가 자동으로 생성되기 때문에 코드가 간결해진다고 하네요!

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/MovieResponse.java
movieResponseDto이런식으로 DTO는 명시해주면 좋을거같아요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/MovieResponse.java
setter를 사용하면 객체 지향 원리 ocp(확장에 대해서는 열려있어야하고 수정에 대해서는 닫혀있어야한다) 를 지키지 않게 됩니다!
되도록 생성시 롬복의 Builder 어노테이션을 사용하고 수정시에만 따로 메서드를 지정해서 하면좋을거같아요
[관련링크 첨부해서 확인해보시면좋을거같아요!](https://mjoo1106.tistory.com/entry/Spring-Setter-vs-Builder)

---
생성자에 @Builder어노테이션을 달아주세요! -> 빌더로 모든 필드를 가지는 객체를 생성하는 생성자를 자유롭게 생성합니다

@Builder 를 등록하는 방법은 생성자와 클래스에 선언하는 방법이 있습니다
전자는 모든 매개변수가 생성자의 대상이 되어 객체 생성시 받지 않아야할 매개변수들도 빌더에 노출이됩니다
따라서 후자를 사용해 필요한 것만 생성자로 지정합시다
그리고 @NoArgsConstructor(access = AccessLevel.PROTECTED) 어노테이션이 있는데 해당 어노테이션은 기본생성자의 접근제어를 PROPECTED 로 하라는 것인데 이렇게 설정하게 되면 기본생성자의 생성을 막고, 무분별한 객체 생성에 대해 체크할 수 있어 안전하다고 합니다.

결론적으로 @NoArgsConstructor(access = AccessLevel.PROTECTED) 어노테이션 과 @Builder 생성자 어노테이션을 함께 사용하여 객체 지향 원칙을 지키면 좋을거 같아요!

아래문서 참고해서 공부해보고 모르는 거 있으면 같이 토론해봐요!
https://cobbybb.tistory.com/14
https://yeon-kr.tistory.com/176
https://velog.io/@cieroyou/Builder-%EC%82%AC%EC%9A%A9%EB%B2%95

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/SearchDto.java
마찬가지로 setter 삭제하고 private final String search 와 @RequiredArgsContructor 어노테이션을 사용해 생성자 주입(DI 세가지 방법 중 제일 권장됨) 을 사용해주세요

[관련 링크 첨부합니다](https://medium.com/webeveloper/requiredargsconstructor-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85-dependency-injection-4f1b0ac33561)

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/Star.java
마찬가지로 setter 삭제하고 생성자 주입 활용해주세요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/StarRepository.java
jpql 말고 jpa로 한번 작성해보실래요??!

[관련문서 참고해보시고 모르는 거 물어봐주세요!](https://geonoo.tistory.com/149)

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/StarRepository.java
jpql은 런타임 에러 가능성이 있어서 위험하다고 합니다!
https://velog.io/@djc06048/ORM-JPA-Hibernate-JPQL-QueryDSL-%EC%B4%9D-%EC%A0%95%EB%A6%AC#jpql-querydsl

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
이 부분도 @Autowired 필드 주입말고 생성자 주입으로 바꿔주세요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/star/StarService.java
이 부분도 생성자 주입으로 바꿔주세요

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/star/Star.java
오오 연관관계 맵핑은 좋아요!!

2023-07-02 06:58 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
convertToMovieResponse 이거는 무슨함수인가요?!

2023-07-03 07:41 UTC, J-neat commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
StarScore 와 Movie Entity 의 필요한 정보들을 하나로 묶어서 관리하기 위해 생성한 함수입니다!

2023-07-03 15:20 UTC, djc06048 approved these changes

2023-07-03 15:21 UTC, djc06048 approved these changes

2023-07-03 15:21 UTC, djc06048 approved these changes

2023-07-03 15:22 UTC, djc06048 approved these changes

2023-07-03 15:39 UTC, djc06048 approved these changes

2023-07-03 15:39 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/movie/dto/MovieResponseDto.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
이 부분은 필요없을거같아요
해당 코드는 기본 생성자의 접근 제한자가 protected로 설정되는건데 
여기서 빌더로 생성자를 생성했으니말이죠

2023-07-03 15:39 UTC, djc06048 approved these changes

2023-07-04 08:13 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
> +        );
Builder 패턴을 적용해보는 것을 고려해보시는 것도 좋을거 같아요!

2023-07-04 08:13 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java
> +            e.printStackTrace();
service 계층에서 오류를 printStackTrace를 던진 이유가 있을까요?

2023-07-04 08:13 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/movie/MovieController.java
> +    public List<Map<String, Object>> getPopularMovies() {
Object로 타입을 선정하신 이유가 있으실까요? 이 부분은 Object로 하면 모호하게 값이 전달되어서 확실한 타입으로 전달해줘야 될 거 같아요!

2023-07-04 10:27 UTC, J-neat commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieSearchService.java
> +        );
감사합니다. Builder패턴을 통해 수정했습니다!

2023-07-04 10:32 UTC, J-neat commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java
> +            e.printStackTrace();
JSON 파싱을 처음해봐서 혹시나 예외 처리 오류가 발생해서 나중에 디버깅할 때 도움이 될까 하고 넣어뒀었습니다.

2023-07-04 14:09 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/movie/MovieCrawlService.java
> +            e.printStackTrace();
예외처리 구체화하면 좋을거같아요

2023-07-05 04:13 UTC, khyojun commented
나중에 올리시기 전에 꼭! conflict된다는 파일에 대해서 resolve conflicts 누르셔서 conflicts 해결하고 올리셨으면 좋겠습니다!

2023-07-07 01:46 UTC, merged