당일 기준 리뷰 좋아요 많이 받은 베스트 리뷰 관련 api 구현
IT-NOVATION/BackEnd pull request #37
Opened 2023-07-05 17:33 UTC by khyojun

![image](https://github.com/IT-NOVATION/BackEnd/assets/38220795/1e752521-0b9b-4bca-8bf0-309bf47289b6)

![image](https://github.com/IT-NOVATION/BackEnd/assets/38220795/3bc958ee-a9d5-44ce-a84e-556da64d1db4)

![image](https://github.com/IT-NOVATION/BackEnd/assets/38220795/72c30543-5710-4d5b-89ea-e5e4bc187dac)

위 db를 토대로 선정하여서 응답 결과를 보냈습니다!

이번 코드에서 여러가지 Repository의 수정이 있습니다. jpql을 작성하다 보니 쿼리문이 많이 복잡해져서 이 부분 논의가 꼭! 필요할 거 같습니다.

이후의 다른 비슷한 기능에도 이러한 방식으로 복잡한 쿼리가 동작해야 될 수도 있을거 같습니다.

2023-07-06 06:14 UTC, stakbucks requested changes
<img width="770" alt="스크린샷 2023-07-06 오후 3 11 29" src="https://github.com/IT-NOVATION/BackEnd/assets/107744534/eea11915-da1a-49f1-a376-e49ec7c08869">
<img width="1432" alt="스크린샷 2023-07-06 오후 3 12 03" src="https://github.com/IT-NOVATION/BackEnd/assets/107744534/92582d83-3031-4d2f-9fdd-794c2d5ab75e">
로그인 했을 때는 위와 같이 데이터 잘 받아와 집니다!!
근데 로그인 안해서 토큰이 유효하지 않을 때 데이터가 안받아와지네요. securityconfig에 "today/**" 있는데도 안돼요. 이것만 고치면 될듯합니당

2023-07-07 09:01 UTC, djc06048 reviewed
WOW 🔥

2023-07-07 09:01 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/config/SecurityConfig.java
어제 회의 때말한대로 requestMatcher 에 추가해주세요 😿

2023-07-07 13:23 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/domain/reviewLike/ReviewLike.java
> +    @ManyToOne
깜빡했네요! 설정 다시 해놓겠습니다!

2023-07-08 02:13 UTC, J-neat approved these changes
LGTM

2023-07-08 02:32 UTC, stakbucks approved these changes

2023-07-08 02:33 UTC, merged