Feature/single star 기능 추가
IT-NOVATION/BackEnd pull request #47
Opened 2023-07-10 07:14 UTC by J-neat

<img width="637" alt="image" src="https://github.com/IT-NOVATION/BackEnd/assets/115057370/be59597b-88b9-4bed-ac55-c4586088db0b">

개별 영화 페이지에서 평점을 기록하는 기능을 추가했습니다.
1. 해당 유저가 존재하지 않는 경우 "해당 유저가 존재하지 않습니다." 메세지를 띄웁니다.
2. 해당 영화가 존재하지 않는 경우 "해당 영가 존재하지 않습니다."  메세지를 띄웁니다.
3. 만약 영화의 별점을 처음 평가한다면 새롭게 별점이 테이블에 추가가 됩니다.
4. 만약 영화의 별점을 다시 평가한다면 별점이 테이블에서 업데이트 됩니다.

2023-07-10 14:53 UTC, khyojun approved these changes
LGTM

2023-07-11 11:39 UTC, djc06048 requested changes

2023-07-11 11:39 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/star/StarService.java
> +        return ResponseEntity.status(HttpStatus.OK).body(200);
이미 응답 헤더로 200을 줬기 때문에 body에는 아무런 응답이 가지 않아도 됩니다~!

2023-07-11 12:20 UTC, djc06048 approved these changes

2023-07-11 13:15 UTC, merged