Feature/single review count
IT-NOVATION/BackEnd pull request #48
Opened 2023-07-10 08:24 UTC by J-neat

<img width="632" alt="image" src="https://github.com/IT-NOVATION/BackEnd/assets/115057370/ddf3fe1e-44b0-4da8-ac7a-7dc29d21faef">

1. PathVariable로 movieId를 넘겨 받으면 reviewCount가 Long 타입으로 {"reviewCount":2} 다음과 같이 반환됩니다.

2023-07-10 14:55 UTC, khyojun approved these changes
LGTM

Conflict 만 잘 해결해주세요

2023-07-10 14:56 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/single/SingleController.java
> +@RequestMapping("/test/single")
요기에 나중에 올리실 때는 /test 를 빼고 /single로 올리는게 어땠을까요?

2023-07-10 14:58 UTC, khyojun reviewed
Conflict 잘 해결해주세요

2023-07-11 11:41 UTC, djc06048 requested changes
효준님이 말씀하신 부분만 고치면될거같아요!

2023-07-11 12:22 UTC, djc06048 approved these changes

2023-07-11 12:22 UTC, khyojun approved these changes

2023-07-11 13:17 UTC, merged