어제 요청했던 사항들 추가(리뷰 읽기)
IT-NOVATION/BackEnd pull request #60
Opened 2023-07-16 10:59 UTC by khyojun

### 패치노트

1. following, follower 명수를 response에 추가
2. login한 유저와 review를 작성한 유저와의 관계 response 추가 (follow했는지, 리뷰에 대해 좋아요를 눌렀는지)

2023-07-16 14:49 UTC, djc06048 approved these changes

2023-07-17 06:24 UTC, J-neat commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java
> +                loginUser = userRepository.findByEmail(email);
여기선 token을 추출해서 바로 유저를 확인하지는 못하나요?

2023-07-17 07:51 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/service/review/ReviewService.java
> +                loginUser = userRepository.findByEmail(email);
이전 호출한 컨트롤러에서 작업을 진행하게 되었습니다. 이유를 말하자면 그렇게 할 경우 또 parameter를 전달해서 앞의 작업을 처리하기 때문에 미리 앞에서 처리하고 난 후에 넘어올 수 있도록 하였습니다.

2023-07-17 11:16 UTC, stakbucks requested changes
고생 많으십니다. 몇가지 문제점들과 의문점이 있어서 남깁니다. 확인 부탁드려용😘

- folllowerNum → followerNum 으로 수정하면 좋을듯
- 로그인 안하면 에러 발생 ⇒ 리뷰 읽기 불가
- 좋아요 누른적 있으면 pushedReviewLike 값이 true, 없으면 false가 아닌 null이 응답으로 옴. 의도한 건지?

2023-07-17 11:25 UTC, stakbucks commented
<img width="492" alt="스크린샷 2023-07-17 오후 8 23 36" src="https://github.com/IT-NOVATION/BackEnd/assets/107744534/d583402b-d07f-4807-b3ad-00bf777b3b52">
리뷰 읽기 페이지 화면 기획 확정된 거 보면 해당 리뷰에 대한 좋아요 누른 유저들의 목록 + 현재 보고 있는 유저의 팔로우 여부 가 필요한데, 이걸 무비로그 처럼 한번에 하나의 api 응답에 담아서 줄지 아니면 다른 방법으로 할지 의견 주세요

2023-07-17 11:28 UTC, djc06048 commented
> 고생 많으십니다. 몇가지 문제점들과 의문점이 있어서 남깁니다. 확인 부탁드려용😘
> 
> * folllowerNum → followerNum 으로 수정하면 좋을듯
> * 로그인 안하면 에러 발생 ⇒ 리뷰 읽기 불가
> * 좋아요 누른적 있으면 pushedReviewLike 값이 true, 없으면 false가 아닌 null이 응답으로 옴. 의도한 건지?

2번째 문제는 해결했어요
나머지는 효준씨가 해결해주세용~

2023-07-17 11:51 UTC, djc06048 commented
따로 주는게 좋을거같네요 저는😶‍🌫️🙄😲
2023년 7월 17일 (월) 오후 8:25, stakbucks ***@***.***>님이 작성:

> [image: 스크린샷 2023-07-17 오후 8 23 36]
> <https://user-images.githubusercontent.com/107744534/253926713-d583402b-d07f-4807-b3ad-00bf777b3b52.png>
> 리뷰 읽기 페이지 화면 기획 확정된 거 보면 해당 리뷰에 대한 좋아요 누른 유저들의 목록 + 현재 보고 있는 유저의 팔로우 여부 가
> 필요한데, 이걸 무비로그 처럼 한번에 하나의 api 응답에 담아서 줄지 아니면 다른 방법으로 할지 의견 주세요
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IT-NOVATION/BackEnd/pull/60#issuecomment-1637931606>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5DRT5X5O2PN4IC2RJTOLDXQUOJRANCNFSM6AAAAAA2L3Y3DQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-17 11:55 UTC, stakbucks commented
![스크린샷 2023-07-17 오후 8 55 04](https://github.com/IT-NOVATION/BackEnd/assets/107744534/fbea86ce-6ae2-4e0f-8d71-2a0909f3b640)
여기두 오타.. Premiumpremiumpremium

2023-07-17 12:15 UTC, stakbucks commented
저 그리고 또 궁금한게 있는데, 디비에 들어가는 시간은 우리나라 시간이 아닌가요? 항상 다르네요. 예를 들어 방금 21시에 작성한 리뷰가 디비에 보면 12시에 작성됐다고 나옵니다.

2023-07-17 13:49 UTC, stakbucks commented
김효준씨 PREMIUM 깜지 50장 써오세요😡

2023-07-18 00:44 UTC, khyojun commented
> <img alt="스크린샷 2023-07-17 오후 8 23 36" width="492" src="https://user-images.githubusercontent.com/107744534/253926713-d583402b-d07f-4807-b3ad-00bf777b3b52.png"> 리뷰 읽기 페이지 화면 기획 확정된 거 보면 해당 리뷰에 대한 좋아요 누른 유저들의 목록 + 현재 보고 있는 유저의 팔로우 여부 가 필요한데, 이걸 무비로그 처럼 한번에 하나의 api 응답에 담아서 줄지 아니면 다른 방법으로 할지 의견 주세요

일단 편하신대로 기능이 되게 하는 방법대로 가면 좋을거 같은데 제 생각은 따로 보내는게 더 명시적으로 나중에 알아보기 좋을거 같아요!

2023-07-20 01:21 UTC, djc06048 commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/singleMoviePage/SingleMoviePageController.java
> +    public ResponseEntity moviePage(@PathVariable Long movieId, HttpServletRequest request){
여기 request 객체는 어디에 사용되나요?

2023-07-20 06:20 UTC, khyojun commented on ItNovation/src/main/java/com/ItsTime/ItNovation/controller/singleMoviePage/SingleMoviePageController.java
> +    public ResponseEntity moviePage(@PathVariable Long movieId, HttpServletRequest request){
loginUser에 대한 정보를 받아야 해서 token을 추출하는데 사용을 하였습니다!

2023-07-21 10:28 UTC, stakbucks approved these changes

2023-07-21 10:29 UTC, stakbucks approved these changes

2023-07-21 10:29 UTC, merged